name: www.miamistreetcustoms.com
favicon: null
layout_spectrum: 0.49958
typography_spectrum: 0.05866
title: Miami Street Customs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ddcb'
    - '#00b3a7'
    - '#007b73'
    - '#00a195'
    - '#000000'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
